// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createEntry = `-- name: CreateEntry :one
INSERT INTO entries(
id,
transaction_id,  
account_id,  
amount_minor,
currency
)VALUES(
$1, $2, $3, $4, $5
)
RETURNING id, transaction_id, account_id, amount_minor, currency, created_at
`

type CreateEntryParams struct {
	ID            uuid.UUID
	TransactionID uuid.UUID
	AccountID     uuid.UUID
	AmountMinor   int64
	Currency      string
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error) {
	row := q.db.QueryRow(ctx, createEntry,
		arg.ID,
		arg.TransactionID,
		arg.AccountID,
		arg.AmountMinor,
		arg.Currency,
	)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.AccountID,
		&i.AmountMinor,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions(
    id,
    idempotency_key, 
    description 
) VALUES (
    $1, $2, $3
)
RETURNING id, idempotency_key, description, created_at
`

type CreateTransactionParams struct {
	ID             uuid.UUID
	IdempotencyKey *string
	Description    string
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction, arg.ID, arg.IdempotencyKey, arg.Description)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one

SELECT id, owner_id, type, currency, balance_minor, version, created_at, updated_at
FROM accounts
WHERE id = $1
`

// Queries in this directory are compiled into type-safe Go by sqlc.
// Run: make sqlc
//
// TODO(phase1): write the queries you need. Two are sketched below to show the
// annotation format; the rest are yours.
func (q *Queries) GetAccountByID(ctx context.Context, id uuid.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Type,
		&i.Currency,
		&i.BalanceMinor,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockAccountsForUpdate = `-- name: LockAccountsForUpdate :many
SELECT id, owner_id, type, currency, balance_minor, version, created_at, updated_at
FROM accounts
WHERE id = ANY($1::uuid[])
ORDER BY id
FOR UPDATE
`

// Deterministic ordering prevents deadlocks between concurrent opposing
// transfers. See the note in internal/storage/postgres/db.go.
func (q *Queries) LockAccountsForUpdate(ctx context.Context, accountIds []uuid.UUID) ([]Account, error) {
	rows, err := q.db.Query(ctx, lockAccountsForUpdate, accountIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Type,
			&i.Currency,
			&i.BalanceMinor,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccountBalance = `-- name: UpdateAccountBalance :one
UPDATE accounts
SET
    balance_minor = $2,
    version = version + 1,
    updated_at = NOW()
WHERE id = $1
RETURNING id, owner_id, type, currency, balance_minor, version, created_at, updated_at
`

type UpdateAccountBalanceParams struct {
	ID           uuid.UUID
	BalanceMinor int64
}

// Concurrency is guarded by LockAccountsForUpdate (FOR UPDATE); version is bumped for audit/observability only.
func (q *Queries) UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccountBalance, arg.ID, arg.BalanceMinor)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Type,
		&i.Currency,
		&i.BalanceMinor,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
