// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID           uuid.UUID
	OwnerID      uuid.NullUUID
	Type         string
	Currency     string
	BalanceMinor int64
	Version      int64
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type BalanceDrift struct {
	AccountID       uuid.UUID
	StoredBalance   int64
	ComputedBalance interface{}
	Drift           int32
}

type Entry struct {
	ID            uuid.UUID
	TransactionID uuid.UUID
	AccountID     uuid.UUID
	AmountMinor   int64
	Currency      string
	CreatedAt     pgtype.Timestamptz
}

type IdempotencyKey struct {
	Key            string
	UserID         uuid.UUID
	RequestHash    string
	Status         string
	ResponseStatus *int32
	ResponseBody   []byte
	TransactionID  uuid.NullUUID
	CreatedAt      pgtype.Timestamptz
	CompletedAt    pgtype.Timestamptz
}

type Transaction struct {
	ID             uuid.UUID
	IdempotencyKey *string
	Description    string
	CreatedAt      pgtype.Timestamptz
}

type User struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	Role         string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
