// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	// Queries in this directory are compiled into type-safe Go by sqlc.
	// Run: make sqlc
	//
	// TODO(phase1): write the queries you need. Two are sketched below to show the
	// annotation format; the rest are yours.
	GetAccountByID(ctx context.Context, id uuid.UUID) (Account, error)
	// Deterministic ordering prevents deadlocks between concurrent opposing
	// transfers. See the note in internal/storage/postgres/db.go.
	LockAccountsForUpdate(ctx context.Context, accountIds []uuid.UUID) ([]Account, error)
	// relative update prevents lost updates; the lock gives the funds check a current balance and, taken in ID order, prevents deadlocks.
	UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) (Account, error)
}

var _ Querier = (*Queries)(nil)
